version: "3.8"

services:
  gh-runner-local:
    image: benthebuilder/cglabs-gh-runner:latest
    network_mode: host
    dns:
      - 192.168.10.11
      - 192.168.10.12
    container_name: GH-RUNNER-LOCAL
    deploy: 
      mode: replicated
      replicas: 1
    environment:
      - TOKEN=${GH_TOKEN}
      - REPO="benthecloudguy/home-network"
      - SSH_TMP_DIR="/home/docker/tmp/"
    volumes:
      - C:\Users\BenTheBuilder\.ssh:/home/docker/tmp
    restart: unless-stopped