name: Test Docker GH Runner

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: test for Ansible
        shell: bash
        run: cat /etc/os-release 